# Generated by Django 5.2 on 2025-05-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0001_initial"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(default="Нет описания"),
        ),
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(to="labels.label"),
        ),
    ]
