# Generated by Django 5.2 on 2025-05-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="author",
        ),
    ]
