# Generated by Django 5.2.1 on 2025-05-29 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_task_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="assignee",
        ),
        migrations.AddField(
            model_name="task",
            name="executor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_executor",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
