# Generated by Django 5.2.1 on 2025-06-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0001_initial"),
        ("tasks", "0008_alter_task_executor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProxy",
        ),
        migrations.AlterField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(blank=True, null=True, to="labels.label"),
        ),
    ]
